### ISSUE TITLE
Storyboard can't find PMSuperButton which integrated through Carthage

### ISSUE THREAD

**Issue by Banck** [Codeido/PMSuperButton#12]
Hello!
I've placed UIButton in my storyboard and tried to type PMSuperButton in class, but there is no PMSuperButton. If wrote it there, then error:
 Unknown class PMSuperButton in Interface Builder file.
But in .swift files I can import PMSuperButton , create and works with them.
Thanks!

**Comment by pmusolino** [comment]
Hi @Banck,

I think that this is an Xcode bug. 

You must save your work and quit Xcode.

When you run Xcode again, you will see PMSuperButton class.

Let me know.
Thanks
-Paolo

**Comment by Banck** [comment]
@pmusolino Hey! No, it doesn't work. Other frameworks are working fine.

**Comment by pmusolino** [comment]
Can you show me how you imported the library? Is it in the right target?

**Comment by Banck** [comment]
@pmusolino 
In cartfile:
github "pmusolino/PMSuperButton"

Then added to the linked frameworks section. The target is setted and it's right target.
In the build phase:
Input file:
$(SRCROOT)/Carthage/Build/iOS/PMSuperButton.framework
output:
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/PMSuperButton.framework

I can import PMSuperButton in any swift file and work with them, but storyboard can't find PMSuperButton.

**Comment by pmusolino** [comment]
If you are the user of a framework with designable support:

- Add the framework (and all its framework dependencies, if any) as embedded binary to your target
- Retrieve the companion source file from the framework bundle and copy it into your project, adding it to your target. Adding the file located within the framework or using a symbolic link sadly does not work, as Xcode does not seem to look within frameworks at all
- Add an instance of the designable view class (MyCustomView in our example above) to a storyboard. Interface Builder should build the project and render the view

This solution is not perfect since you still have to manually copy a supplied source file, which could change between framework versions. But it works pretty well, though, and provides everything required within the framework bundle itself.

More info [here](https://stackoverflow.com/questions/29933691/ibdesignable-from-external-framework).

Let me know if this works for you.
